export const animeData = [
  {
    title: "Leadale no Daichi nite",
    video_url: "//ok.ru/videoembed/3413310179915",
    img_url: "https://www4.0zz0.com/2022/03/10/11/708043335.jpg",
    episodes: "12",
    type: "TV",
    studio: "Currently Airing",
    genre: "Adventure, Fantasy",
    score: "6.7",
    premiered: "Winter 2022",
    duration: "23 min. per ep.",
    quality: "hd",
    img_url_wall: "https://www4.0zz0.com/2022/03/10/11/505176500.jpg",
    title_discription: "In the Land of Leadale",
    discription:
      'The previously bedridden Keina Kagami finds herself in the world of her favorite VRMMORPG—titled Leadale—after the life support keeping her alive fails. Reincarnated in the body of her high-level character, "Cayna," she notices that the world of Leadale is different from what she remembers playing.\n\nAs she comes to learn, two hundred years have passed since she last interacted with the world. However, this does not sadden Cayna—as it means that a new journey awaits her, filled with exciting prospects and unfamiliar faces all waiting to be discovered.',
    views: "15967",
    id: 1,
  },
  {
    title: "Akebi-chan no Sailor-fuku",
    video_url: "//ok.ru/videoembed/3213448055305",
    img_url: "https://www4.0zz0.com/2022/03/10/11/821299476.jpg",
    episodes: "12",
    type: "tv",
    studio: "CloverWorks",
    genre: "Slice of Life",
    score: " 7.56",
    premiered: "Winter 2022",
    duration: "23 min. per ep.",
    quality: "HD",
    img_url_wall: "https://www4.0zz0.com/2022/03/10/11/852803035.jpg",
    title_discription: "Akebi's Sailor Uniform",
    discription:
      "Ever since she was young, Komichi Akebi has always adored sailor uniforms, even going so far as to ask her mother to sew one if she succeeds in getting into her mother's alma mater, Roubai Academy. And thus, when she gets accepted into the prestigious school, Komichi is ecstatic. However, much to her surprise, the middle school no longer uses sailor uniforms as its dress code—making Komichi stand out from her schoolmates. Despite this, Komichi is granted permission to continue wearing the traditional attire.\n\nWith renewed confidence, Komichi meets fascinating classmates as they experience school life together. Under the colorful shower of blossoming prospects, an exciting tomorrow awaits them!",
    views: "15,214",
    data_aired: " Mar 27, 2022",
    status: "Currently Airing",
    " data_aired": "data_aired",
    id: 3,
  },
  {
    title: "Vanitas no Karte Part 2",
    video_url: "//ok.ru/video/5801309833728",
    img_url: "https://www4.0zz0.com/2022/03/10/11/973438556.jpg",
    episodes: "12",
    type: "tv",
    studio: "Bones",
    genre: "Supernatural",
    score: "8.181 ",
    premiered: "Winter 2022",
    duration: "24/min",
    quality: "HD",
    img_url_wall: "https://www4.0zz0.com/2022/03/10/11/980150372.jpg",
    title_discription: "The Case Study of Vanitas",
    discription:
      "Vanitas and Noé Archiviste head out to the town of Gévaudan in search of the \"Beast,\" an enormous wolf-like creature that has slaughtered hundreds of people. Suspecting that the Beast is a curse-bearing vampire, Vanitas primarily aims to heal it using the powers of his grimoire.\n\nAlong the way, the two get separated and suddenly travel back to the past—to the exact moment the Beast is lurking in the woods. After a battle against the gigantic wolf and a vampire hunter, Vanitas decides to team up with Jeanne in order to find Noé. Despite being allies, Jeanne's goal is the opposite of Vanitas', as she was tasked to kill the Beast—suspecting it may be someone she used to know.\n\nMeanwhile, a severely wounded Noé is picked up by the mysterious Chloé d'Apchier and her servant. Like Noé, Chloé is a vampire whose existence was erased from the public's knowledge. She has been a guardian for future generations and once tried to find a way to become human again. While Noé is grateful to Chloé for her hospitality, little does he know that she might be siding with forces far more dangerous than the Beast itself.",
    views: "17,578 ",
    data_aired: "Apr 2, 2022",
    status: "Currently Airing",
    id: 5,
  },
  {
    title: "Kimetsu no Yaiba: Yuukaku-hen",
    video_url: "//ok.ru/video/3914285320747",
    img_url: "https://www5.0zz0.com/2022/03/10/12/281106182.jpg",
    episodes: "11",
    type: "tv",
    studio: "ufotable",
    genre: "Action, Supernatural",
    score: "8.911 ",
    premiered: "Winter 2022",
    duration: "26 min. per ep.",
    quality: "HD",
    img_url_wall: "https://www5.0zz0.com/2022/03/10/12/659736938.jpg",
    title_discription:
      "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc",
    discription:
      "The devastation of the Mugen Train incident still weighs heavily on the members of the Demon Slayer Corps. Despite being given time to recover, life must go on, as the wicked never sleep: a vicious demon is terrorizing the alluring women of the Yoshiwara Entertainment District. The Sound Pillar, Tengen Uzui, and his three wives are on the case. However, when he soon loses contact with his spouses, Tengen fears the worst and enlists the help of Tanjirou Kamado, Zenitsu Agatsuma, and Inosuke Hashibira to infiltrate the district's most prominent houses and locate the depraved Upper Rank demon.",
    views: "338,984 ",
    data_aired: "Feb 13, 2022",
    status: "Finished Airing",
    id: 6,
  },
  {
    title: "Megaton-kyuu Musashi",
    video_url: "//ok.ru/video/3217491954219",
    img_url: "https://www6.0zz0.com/2022/03/10/14/899075977.jpg",
    episodes: "13",
    type: "tv",
    studio: "OLM",
    genre: "Action, Sci-Fi",
    score: "6.18",
    premiered: " Fall 2021",
    duration: "24/min",
    quality: "HD",
    img_url_wall: "https://www6.0zz0.com/2022/03/10/14/142402765.jpg",
    title_discription: "Megaton-kyuu Musashi",
    discription:
      'In an ordinary town, there are people who live a peaceful and fulfilling life. But they don\'t know that it is a false peace. The untold truth... The earth has already been destroyed...\n\n99.9% of the human race has been wiped out by a mysterious alien force from outer space. The enemy is named "Dracters." Eventually, a large hole was drilled in the earth and terraformed into a suitable environment for the aliens to live. Humans have no choice but to hide in shelters to escape their eyes. Waiting for the day of resurrection, which they do not know when it will come...\n\nThe inhabitants of the shelter Ixia have had their memories of the day of destruction erased, and live a normal life without knowing anything about it. However, some of them, the "c',
    views: "1,262 ",
    data_aired: " Dec 24, 2021",
    status: "Finished Airing",
    id: 7,
  },
  {
    title: "Gensou Sangokushi: Tengen Reishinki",
    video_url: "//ok.ru/video/3162266077705",
    img_url: "https://www6.0zz0.com/2022/03/10/14/794585330.jpg",
    episodes: "12",
    type: "tv",
    studio: "",
    genre: "Fantasy",
    score: "4.81",
    premiered: "Winter 2022",
    duration: "24/min",
    quality: "HD",
    img_url_wall: "https://www6.0zz0.com/2022/03/10/14/240766834.jpg",
    title_discription: "Fantasia Sango: Realm of Legends",
    discription:
      'In spite of their defeat, the remnant factions of the Taipingtao Revolution continue to resist, plunging China into a seemingly never-ending war. Moreover, the negative emotions left behind by the rebellion\'s massive death toll begin to form miasma—giving birth to malignant beings called the "wangliang." These creatures can possess humans and turn them into horrifying demons, thus bringing about more deaths and miasma and spinning a vicious cycle that inflicts further despair upon the land.\n\nAs a countermeasure, the immortal deities known as the "Tianyuan" select certain individuals to be "Hunters." Accompanying them are the "Guizhan," specialists created by the Tianyuan who can absorb miasma and transform into demons themselves, acting as indispensable weapons against the wangliang.\n\nAfter a tragic accident involving an out-of-control Guizhan causes the disbandment of the Sixth Hunter Unit, the Tianyuan designate three promising Hunters—namely Ji Ying, Qiao Xun, and Yan Ding—to reform the group. However, for an unknown reason, the Tianyuan also appoint Xiao Ling—the young Guizhan responsible for the former unit\'s downfall—to fight alongside the trio. Despite growing tensions, the members of the revived team must settle their differences and collectively use their abilities to attain victory against the common enemy.',
    views: "1,894 ",
    data_aired: "Jan 11, 2022",
    status: "Currently Airing",
    id: 8,
  },
  {
    title: "Mieruko-chan",
    video_url: "//ok.ru/video/3244068637394",
    img_url: "https://www6.0zz0.com/2022/03/10/14/897451693.jpg",
    episodes: "14",
    type: "tv",
    studio: "Passione",
    genre: " Comedy, Horror,",
    score: "7.49",
    premiered: "Fall 2021",
    duration: "24/min",
    quality: "HD",
    img_url_wall: "https://www6.0zz0.com/2022/03/10/14/720107239.jpg",
    title_discription: "Mieruko-chan",
    discription:
      "Miko Yotsuya's eyes water as she fixates on a single spot on her phone—she ignores yet another dreadful, horrific monster that is in her face, uttering the disturbing words: \"Can you see me?\" Before now, Miko enjoyed her unassuming high school days, with late-night horror shows serving only as a form of entertainment. But ever since one fateful day, she is the only person aware of the invisible monsters walking freely among humans.\n\nCourageously, Miko makes a bold decision: she will never, under any condition, acknowledge the presence of the horrid specters. However, even though she pretends they do not exist, she can still see how they disturb the people around her, especially her best friend, the energetic and lovely Hana Yurikawa. In order to protect them from the monsters' annoyances, Miko gives it her best to continue her school life and avoid every troublesome crisis—even when they scare her to tears.",
    views: "126,807 126,807 ",
    data_aired: "Dec 19, 2021",
    status: " Finished Airing",
    id: 9,
  },
  {
    title: "Boku no Hero Academia 4th Season",
    video_url: "//ok.ru/video/3033540856451",
    img_url: "https://www9.0zz0.com/2022/03/10/14/281785074.jpg",
    episodes: "25",
    type: "tv",
    studio: "Bones",
    genre: "Action, Comedy",
    score: "7.97",
    premiered: "Fall 2019",
    duration: "24/min",
    quality: "HD",
    img_url_wall: "https://www9.0zz0.com/2022/03/10/14/355825973.jpg",
    title_discription: "My Hero Academia Season 4",
    discription:
      "After successfully passing his Provisional Hero License exam, Izuku \"Deku\" Midoriya seeks out an extracurricular internship with a professional hero agency. At the recommendation of his mentor All Might, Midoriya lands a position under All Might's former sidekick, Sir Nighteye, now a famous hero in his own right.\n\nAs Midoriya's classmates further their own abilities through various internships, up-and-coming villain Kai Chisaki utilizes his terrifying powers to gather favor in the criminal underworld. Known by the moniker Overhaul, Chisaki's ambitions collide with the League of Villains and its leader, Tomura Shigaraki.\n\nThrough his work with Sir Nighteye, Midoriya discovers Chisaki's crime syndicate and the villain's hostile relationship with a mysterious young girl named Eri. Fearing for the child's safety, Midoriya and his upperclassman Mirio Toogata must work together to put an end to Chisaki's reign of terror.",
    views: "834,682 ",
    data_aired: " Apr 4, 2020",
    status: "Finished Airing",
    id: 10,
  },
  {
    title: "Komi-san wa, Comyushou desu.",
    video_url: "//ok.ru/video/3201953958599",
    img_url: "https://www9.0zz0.com/2022/03/10/14/335330657.jpg",
    episodes: "12",
    type: "tv",
    studio: "OLM",
    genre: "Comedy, Slice of Life",
    score: "8.10",
    premiered: " Fall 2021",
    duration: "23 min. per ep.",
    quality: "HD",
    img_url_wall: "https://www9.0zz0.com/2022/03/10/14/977407699.jpg",
    title_discription: "Komi Can't Communicate",
    discription:
      "Hitohito Tadano is an ordinary boy who heads into his first day of high school with a clear plan: to avoid trouble and do his best to blend in with others. Unfortunately, he fails right away when he takes the seat beside the school's madonna—Shouko Komi. His peers now recognize him as someone to eliminate for a chance to sit next to the most beautiful girl in class.\n\nGorgeous and graceful with long, dark hair, Komi is universally adored and immensely popular despite her mysterious persona. However, unbeknownst to everyone, she has crippling anxiety and a communication disorder which prevents her from wholeheartedly socializing with her classmates.\n\nWhen left alone in the classroom, a chain of events forces Komi to interact with Tadano through writing on the blackboard, as if in a one-way conversation. Being the first person to realize she cannot communicate properly, Tadano picks up the chalk and begins to write as well. He eventually discovers that Komi's goal is to make one hundred friends during her time in high school. To this end, he decides to lend her a helping hand, thus also becoming her first-ever friend.",
    views: "231,843 ",
    data_aired: " Dec 23, 2021",
    status: "Finished Airing",
    id: 11,
  },
  {
    title: "Takt Op. Destiny",
    video_url: "//ok.ru/video/2972449442503",
    img_url: "https://www9.0zz0.com/2022/03/10/14/294462511.jpg",
    episodes: "13",
    type: "tv",
    studio: "Madhouse, MAPPA",
    genre: "Action, Fantasy",
    score: "7.19",
    premiered: "Fall 2021",
    duration: "24/min",
    quality: "HD",
    img_url_wall: "https://www9.0zz0.com/2022/03/10/14/733081434.jpg",
    title_discription: "",
    discription:
      "The United States of America has been in chaos ever since the emergence of D2s, an invasive species originating from a black meteorite that fell to Earth. A public decree banned citizens from playing any melodies, to prevent further casualties caused by the D2s' hatred for music—even now, in 2047, this prohibition is still in effect. Humanity's only form of defense against the D2s are Musicarts, young women representing pieces of classical music; and Conductors, the ones controlling them.\n\nTakt Asahina, an aloof piano prodigy, finds himself transformed into a Conductor following a spontaneous D2 attack. The same incident kills Anna Schneider's younger sister, Cosette, and brings Takt into contact with his Musicart, Destiny. Searching for a means of stabilizing the pact between themselves, Takt and Destiny—alongside Anna—embark on a perilous journey to the Symphonica Headquarters in New York City.\n\nTakt is in a hurry to reach the city so that he can play the piano again, even though his passion attracts the creatures he has come to despise. Meanwhile, Destiny's sense of duty drags the group into trouble along the way. With a D2-infested path and many more arduous obstacles ahead of them, will the trio make it to New York City in one piece?",
    views: "123,112 ",
    data_aired: "Dec 22, 2021",
    status: " Finished Airing",
    id: 12,
  },
  {
    title: "Ousama Ranking",
    video_url: "//ok.ru/video/3275939645961",
    img_url: "https://www6.0zz0.com/2022/03/10/14/265869495.jpg",
    episodes: "23",
    type: "tv",
    studio: "Wit Studio",
    genre: "Adventure, Fantasy",
    score: "8.80",
    premiered: "Fall 2021",
    duration: "22 min. per ep.",
    quality: "HD",
    img_url_wall: "https://www6.0zz0.com/2022/03/10/14/505364856.jpg",
    title_discription: "Ranking of Kings",
    discription:
      "The people of the kingdom look down on the young Prince Bojji, who can neither hear nor speak. They call him \"The Useless Prince\" while jeering at his supposed foolishness.\n\nHowever, while Bojji may not be physically strong, he is certainly not weak of heart. When a chance encounter with a shadow creature should have left him traumatized, it instead makes him believe that he has found a friend amidst those who only choose to notice his shortcomings. He starts meeting with Kage, the shadow, regularly, to the point where even the otherwise abrasive creature begins to warm up to him.\n\nKage and Bojji's unlikely friendship lays the budding foundations of the prince's journey, one where he intends to conquer his fears and insecurities. Despite the constant ridicule he faces, Bojji resolves to fulfill his desire of becoming the best king he can be.",
    views: "86,263 ",
    data_aired: "Mar 25, 2022",
    status: "Currently Airing",
    id: 13,
  },
];
